version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd week6/card-app-redux
      - npm install
  pre_build:
    commands: 
      - npm run test
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'week6/card-app-redux/build'