server:
  port: 8027

info:
  description: This is the account service
  
spring:
  application:
    name: account-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8013/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
    
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'